# ===========================================
# Information Settings
# ===========================================

#navigation
menu:
  article: /
  archives: /archives
  tags: /tags
  about: /about
  RSS: /atom.xml

# favicon
favicon:

# ===========================================
# Color&Schemes Setting
# ===========================================

## Common

# Navigator Language
local-nav: true

# Mobile-Header
# light | dark
mobile-header: light

# Scheme
# banderole | balance
scheme: banderole

# Header Style
# line | block
header-style: line

# theme-style
# default: dark | green | blue | purple
# miku | sakura | snowmiku
theme-style: miku

# ===========================================
# Article Setting
# ===========================================

# Navigator in post
toc: true

# Use copyright infomation
copyright:
  enable: false
  # license:

#Reword button or message(fill your QRCode of any Pay.)
reward:
  enable: false
  # message:
  qrcode:
    # alipay:
    #   url:
    #   message:
    # wechat:
    #   url:
    #   message:
    # paypal:
    #   url:
    #   message:

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments:
  enable: true

  # disqus:
  livere_datauid: MTAyMC80NTM2Ni8yMTg3OQ==

  # changyan:
  #   appid:
  #   appkey:

  # gitalk:
  #   owner:
  #   repo:
  #   client_id:
  #   client_secret:
  #   admin:

# sub //Please just fill out ID.
sub:
#  facebook:
#  twitter:
#  instagram:
#  weibo:
#  zhihu:
  github: sffxzzp
#  linkedin:
#  douban:

#Friend link
# friendLink:

# ===========================================
# Analytics
# ===========================================

analytics:
  google:
  baidu:

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: true

# ===========================================
# Theme Settings
# ===========================================

# instantpage
instantpage: false

# pjax
pjax: true

# mathjax
mathjax: true

# lightbox
lightbox: true

# lazyload
lazyload: true

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# Created Time
since: 2019

# plugin
# plugins:

# about
# self:

# ===========================================
# Search Settings
# ===========================================

# Search
search:
  enable: true
  label: 搜索

# ===========================================
# Documents Styles
# ===========================================

# article-fonts
# default | Simsun | YaHei | Hel | Custom
fonts-style: default

# code-fonts
# default | Custom
code-style: default

# ===========================================
# WebApp Settings (iOS)
# ===========================================


# ===========================================
# Version
# ===========================================
version: 3.0

#theme_author: Co1MugX
